### ISSUE TITLE
Merging pact-parser under Pact Foundation

### ISSUE THREAD

**Issue by mboudreau** [ichyr/pact-parser#2]
Hi,

I wanted to send you an email about this instead, but couldn't find your address anywhere.

I'd like to include your project under the Pact Foundation umbrella as I was personally about to create a repo that does exactly this.  You would gain more momentum and more developers working on this project to hopefully get it out of the door quickly.

If you're interested in doing so, please let me know.  If not, I'll be creating a "competing" library to be used in unison with our current suite.

Cheers,

M

**Comment by ichyr** [comment]
@mboudreau this is awesome. I fully agree to this opportunity.

How the development will start to look like? Should I prepare some vision documents, so people can participate in coordinated development? How this is handled?

E.g. my next step would be introduction of logic that would adapt to the version of pact files to switch between the request matching routines.

**Comment by mboudreau** [comment]
@ichyr great to hear that you're enthusiastic about it :)

Just as a heads up, we are currently implementing this functionality within our new pact shared library (a complete remake of the engine) which will eventually deprecate this project, but in the short term, I think this is a great addition.

If you add me as collaborator on this project, I'll include it within the pact foundation organization and add you as a collaborator for all foundation projects. If you have ideas, todos or other things you want to attach to this project, I'd recommend you create a file (TODO.md?) and commit it to the project.  Then the next step would be to setup the CI on Travis.

Once you're part of the foundation, you can join is on gitter to chat about ongoing development.

Cheers,

M

**Comment by mboudreau** [comment]
@ichyr I've added you as a Collaborator in Pact Foundation.  You can move the repo yourself or give me access to do it :)

**Comment by mboudreau** [comment]
@ichyr I'll close this issue for now. Please join us on gitter :)
